---
title: "Iterations and list columns"
output: html_document
---

I'm an R Markdown document! 

```{r}
library(tidyverse)
library(rvest)
```

## Some lists

```{r}
set.seed(1)
```

```{r}
l = list(
  vec_numeric = 1:4,
  unif_sample = runif(100),
  mat         = matrix(1:8, 2, 4),
  summary     = summary(rnorm(1000))
)
```

```{r}
l$mat
l[['mat']][1,3]
l[[4]]
```

make a list more useful

```{r}
list_norms = 
  list(
    a = rnorm(20, 0, 5),
    b = rnorm(20, 4, 5),
    c = rnorm(20, 0, 10),
    d = rnorm(20, 4, 10)
  )

list_norms[['b']]
```

```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  tibble(
    mean = mean_x, 
    sd = sd_x
  )
}
```

```{r}
mean_and_sd(list_norms[['a']])
mean_and_sd(list_norms[['b']])
mean_and_sd(list_norms[['c']])
mean_and_sd(list_norms[['d']])
```

## use a for loop

```{r}
output = vector('list', length = 4)

for (i in 1:4) {
  output[[i]] = mean_and_sd(list_norms[[i]])
}
```


## do the same thing 

but with map instead

```{r}
output = map_df(list_norms, mean_and_sd, .id = "input")

output = map_dbl(list_norms, IQR)
```

## list columns

```{r}
listcol_df = 
  tibble(
    name = c("a", "b", "c", "d"),
    samp = list_norms
  )

listcol_df|>
  filter(name %in% c('a', 'b'))

listcol_df|>
  select(-samp)
```

```{r}
mean_and_sd(listcol_df$samp[['a']])
mean_and_sd(listcol_df$samp[['b']])
```

```{r}
listcol_df|>
  mutate(output = map(samp,mean_and_sd),
         iqr = map_dbl(samp, IQR))

listcol_df|>
  mutate(output = map(samp,mean_and_sd),
         iqr = map_dbl(samp, IQR))|>
  select(-samp)|>
  unnest(output)
```

## NSDUH

```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

nsduh_html = read_html(nsduh_url)
```

```{r}
nsduh_table_format(nsduh_html,1)
nsduh_table_format(nsduh_html,4)
nsduh_table_format(nsduh_html,5)
```

```{r}
nsduh_df <- 
  tibble(
    drug = c("marj", "cocaine", "heroine"),
    table_n = c(1, 4, 5)
  )|>
  mutate(table = map(table_n, nsduh_table_format, html = nsduh_html))|>
  unnest(table)
```

```{r}
nsduh_df|>
  filter(State == 'New York')
```

```{r}
nsduh_df <- 
  tibble(
    drug = c("marj", "cocaine", "heroine"),
    table_n = c(1, 4, 5)
  )|>
  mutate(table = map(table_n, \(x) nsduh_table_format(html = nsduh_html, table_num = x)))|>
  unnest(table)
```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

```{r}
weather_nest = 
  nest(weather_df, data = date:tmin)

weather_nest
```

```{r}
weather_nest[['data']][[1]]
```

```{r}
lm(tmax~tmin, data =weather_nest[['data']][[1]])
lm(tmax~tmin, data =weather_nest[['data']][[2]])
lm(tmax~tmin, data =weather_nest[['data']][[3]])
```











