---
title: "Simulatiion"
output: html_document
---

I'm an R Markdown document! 

```{r}
library(tidyverse)
set.seed(1)
```

## writing a simulation function

```{r}
sim_mean_sd = function(n, mu = 2, sigma = 3) {
  
  sim_data = tibble(
    x = rnorm(n, mean = mu, sd = sigma),
  )
  
  output = 
    sim_data |> 
    summarize(
      mu_hat = mean(x),
      sigma_hat = sd(x)
    )
  return(output)
}
sim_mean_sd(30)
```

run using a for loop?

```{r}
output = vector("list", 1000)

for (i in 1:1000) {
  output[[i]] = sim_mean_sd(30)
}

output
```

```{r}
sim_results = bind_rows(output)|>
  summarise(
    ave_mean = mean(mu_hat),
    sd_mean = sd(mu_hat)
  )
```

```{r}
sim_res = 
  tibble(
    iter = 1:1000
  )|>
  mutate(samp_res = map(iter, sim_mean_sd, n= 30))|>
  unnest(samp_res)
```

```{r}
sim_res = 
  expand_grid(
    n = c(10,30,60,100),
    iter = 1:1000
  ) |> 
  mutate(
    estimate_df = map(n, sim_mean_sd)
  ) |> 
  unnest(estimate_df)
```

```{r}
sim_res|>
  group_by(n)|>
  summarise(
    se = sd(mu_hat)
  )
```

```{r}
sim_res |>
  filter(n ==10)|>
  ggplot(aes(x = mu_hat)) + 
  geom_density()
```
```{r}
sim_res |>
  mutate(n = str_c('n = ', n))|>
  ggplot(aes(x = n, y = mu_hat)) + 
  geom_violin()
```
```{r}
sim_regression = function(n, beta0 = 2, beta1 = 3) {
  
  sim_data = 
    tibble(
      x = rnorm(n, mean = 1, sd = 1),
      y = beta0 + beta1 * x + rnorm(n, 0, 1)
    )
  lm_fit = lm(y~x, data = sim_data)
  out_df = 
    tibble(
      beta0_hat = coef(lm_fit)[1],
      beta1_hat = coef(lm_fit)[2]
    )
  return(out_df)
}
```

```{r}
sim_results_df = 
  expand_grid(
    sample_size = 30,
    iter = 1:1000
  ) |> 
  mutate(lm_res = map(sample_size, sim_regression))|>
  unnest(lm_res)

sim_results_df|>
  ggplot(aes(x = beta1_hat))+
  geom_histogram()
```

```{r}
sim_results_df|>
  ggplot(aes(x = beta0_hat, y = beta1_hat))+
  geom_point()
```
## birthday problem!

```{r}
bday_sim <- function(n){
bdays = sample(1:365, size = n, replace = T)
duplicate = length(unique(bdays))<n
return(duplicate)
}
```

```{r}
sim_res = 
  expand_grid(
    n = 2:50,
    iter = 1:10000
  )|>
  mutate(res = map_lgl(n, bday_sim))|>
  group_by(n)|>
  summarise(prob = mean(res))
```

```{r}
sim_res|>
  ggplot(aes(x = n, y = prob))+
  geom_line()
```







