---
title: "functions"
output: html_document
---

I'm an R Markdown document! 


```{r}
library(tidyverse)
library(rvest)
```

```{r}
set.seed(2)
x_vec = rnorm(25, mean = 10, sd = 3.5)

(x_vec - mean(x_vec)) / sd(x_vec)
```

```{r}
z_scores = function(x) {
  
  z = (x - mean(x)) / sd(x)
  z
  
}

z_scores(x_vec)
```


```{r}
z_scores(sample(c(TRUE, FALSE), 25, replace = TRUE))
```


```{r}
z_scores = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Z scores cannot be computed for length 1 vectors")
  }
  
  z = mean(x) / sd(x)
  
  z
}
```

## multiple functions

```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  list(mean = mean_x, 
       sd = sd_x)
}
```

```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  tibble(
    mean = mean_x, 
    sd = sd_x
  )
}
```

## simulation function to check sample mean and sd

```{r}
sim_mean_sd = function(n, mu, sigma) {
  
  sim_data = tibble(
    x = rnorm(n, mean = mu, sd = sigma),
  )
  
  sim_data |> 
    summarize(
      mu_hat = mean(x),
      sigma_hat = sd(x)
    )
}

sim_mean_sd(3000, 5, 12)
```

```{r}
fellowship_ring = readxl::read_excel("./LotR_Words.xlsx", range = "B3:D6") |>
  mutate(movie = "fellowship_ring")|>
  janitor::clean_names()

two_towers = readxl::read_excel("./LotR_Words.xlsx", range = "F3:H6") |>
  mutate(movie = "two_towers")|>
  janitor::clean_names()

return_king = readxl::read_excel("./LotR_Words.xlsx", range = "J3:L6") |>
  mutate(movie = "return_king")|>
  janitor::clean_names()

lotr_tidy = bind_rows(fellowship_ring, two_towers, return_king) |>
  janitor::clean_names() |>
  pivot_longer(
    female:male,
    names_to = "sex",
    values_to = "words") |> 
  mutate(race = str_to_lower(race)) |> 
  select(movie, everything()) 
```

```{r}
lotr_load_and_tidy = function(path, range, movie_name) {
  
  df = 
    readxl::read_excel(path, range = range) |>
    janitor::clean_names() |>
    pivot_longer(
      female:male,
      names_to = "sex",
      values_to = "words") |>
    mutate(
      race = str_to_lower(race),
      movie = movie_name) |> 
    select(movie, everything())
  
  df
  
}

lotr_tidy = 
  bind_rows(
    lotr_load_and_tidy("./LotR_Words.xlsx", "B3:D6", "fellowship_ring"),
    lotr_load_and_tidy("./LotR_Words.xlsx", "F3:H6", "two_towers"),
    lotr_load_and_tidy("./LotR_Words.xlsx", "J3:L6", "return_king"))
```

## NSDUH

```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

nsduh_html = read_html(nsduh_url)

data_marj = 
  nsduh_html |> 
  html_table() |> 
  nth(1) |>
  slice(-1)|>
  mutate(drug = 'marj')

cocaine_table = 
  nsduh_html |> 
  html_table() |> 
  nth(4) |>
  slice(-1)|> 
  mutate(drug = 'cocaine')
heroin_table = 
  nsduh_html |> 
  html_table() |> 
  nth(5) |>
  slice(-1)|> 
  mutate(drug = 'heroin')

```

```{r}
nsduh_table_format <- function(html, table_num, table_name){
  out_table = nsduh_html |> 
  html_table() |> 
  nth(table_num) |>
  slice(-1)|> 
  mutate(drug = table_name)
  
  return(out_table)
    
}

source('./nsduh_table_format.R')
```


